name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run tests
        run: pytest -q

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Helm Lint
        run: helm lint helm/profile-service

      - name: Render Helm Templates
        run: helm template profile-service helm/profile-service

      - name: Build Docker Image
        run: |
          docker build -t profile-service:${{ github.sha }} .

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: profile-service:${{ github.sha }}
